name: C++ 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up compiler and Google Test
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ cmake make clang-tidy
          git clone https://github.com/google/googletest.git
          cd googletest
          cmake .
          make
          sudo make install

      - name: Build project
        run: |
          g++ -std=c++17 -o my_program Test.cpp lab6.cpp -lgtest -lgtest_main -pthread

      - name: Run tests
        run: |
          chmod +x my_program
          ./my_program