name: Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: "rmomm"
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/rmomm/lab6:latest
            ghcr.io/rmomm/lab6:${{ github.sha }}

  test:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Run tests inside container
        run: |
          docker pull ghcr.io/rmomm/lab6:latest
          docker run --rm ghcr.io/rmomm/lab6:latest ./test_program
          